### PR TITLE
Add code quality badge

### PR DESCRIPTION
**Pull request by roebuk**

### CODE REVIEW

**Comment by arshadkazmi42** [comment]
Looks good. Can you add the issue number in the first comment on PR. I will merge it as soon as that change is done.

**Comment by roebuk** [comment]
This PR closes issue 24 https://github.com/arshadkazmi42/simple-date-validator/issues/24

**Comment by arshadkazmi42** [comment]
Merged 👍 congrats on your first PR.
Thank you for working on this.

**Comment by roebuk** [comment]
Thank you for the nice easy introduction 👍

**Pull request merged**
